# Generated by Django 4.0.1 on 2022-06-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='product_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='product_model',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='product_rate',
        ),
    ]
