# Generated by Django 4.0.1 on 2022-06-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_rename_brand_product_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_rate',
            new_name='rate',
        ),
    ]
