# Generated by Django 4.0.1 on 2022-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_rename_product_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Mobile',
        ),
    ]
