# Generated by Django 4.0.1 on 2022-06-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_rename_product_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='Product',
        ),
    ]
