# Generated by Django 4.0.1 on 2022-06-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_rename_mobile_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('cpassword', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'userregistration',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.TextField(max_length=30),
        ),
    ]
